AWSTemplateFormatVersion: '2010-09-09'
Description: 'Locus: User-Owned Precision Tracker - S3 Bucket with Object Lock'

Resources:
  LocusDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # We let CloudFormation generate a unique name to avoid collisions.

      VersioningConfiguration:
        Status: Enabled

      ObjectLockEnabled: true

      ObjectLockConfiguration:
        ObjectLockEnabled: 'Enabled'
        Rule:
          DefaultRetention:
            Mode: COMPLIANCE
            Days: 365 # Default retention period (1 year). Can be adjusted.

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: 'The name of the created S3 bucket'
    Value: !Ref LocusDataBucket
  BucketArn:
    Description: 'The ARN of the created S3 bucket'
    Value: !GetAtt LocusDataBucket.Arn
